stages:
  - test
  - lint
  - deploy_integration

# -------------------- Tests --------------------

ft_test:
  stage: test
  image: "registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1"
  script:
    - mkdir -p build; cd build
    - cmake ../test; make -j
    - ./test_edcc

samples_test:
  stage: test
  image: "registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1"
  script:
    - mkdir -p build; cd build
    - cmake ..; make -j; make install
    - make -j run_py_sample

# -------------------- Lints --------------------