stages:
  - tests_and_lints
  - build_image

variables:
  IMAGE: registry.cn-hangzhou.aliyuncs.com/leosocy/edcc:master

# -------------------- Tests --------------------
build_test_coverage:
  stage: tests_and_lints
  image:
    name: registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:ci
  coverage: '/lines[\.]+\: (\d+\.\d+)\%/'
  script:
    - mkdir -p build; cd build
    - cmake ../test; make -j
    - ./test_edcc
    - lcov -b . -d edcc -c -o cov.info
    - lcov -r cov.info "/usr/*" "*/thirdparty/*" "*/test/*" -o cov.info -q
    - lcov -l cov.info
    - bash <(curl -s https://codecov.io/bash) -t 24c051cb-8c6f-45e3-afa0-859f2db1418d
    - genhtml -o cov_result cov.info
    - mv cov_result ..
    - rm -rf *
    - cmake ..; make -j; make install
    - make -j run_py_sample
  artifacts:
    name: coverage
    paths:
      - cov_result

# -------------------- Lints --------------------
cppcheck:
  stage: tests_and_lints
  image:
    name: registry.cn-hangzhou.aliyuncs.com/leosocy/cppcheck:1.83
  script:
    - cppcheck --enable=warning --error-exitcode=1 -I source/include source/src

# -------------------- Build onbuild image --------------------

build_image:
  stage: build_image
  only:
    - master
  when: manual
  script:
    - docker build -t ${IMAGE} -f Dockerfile .
    - docker push ${IMAGE}
    