stages:
  - build_test_coverage
  - lint
  - deploy_integration

# -------------------- Tests --------------------
test:
  stage: test
  image: registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1
  script:
    - mkdir -p build; cd build
    - cmake ../test; make -j
    - ./test_edcc
    - lcov -b . -d edcc -c -o cov.info
    - locv -e cov.info "*/EDCC-Palmprint-Recognition/source/*" -o result.info
    - genhtml -o cov_result result.info
    - mv cov_result ..
    - rm -rf *
    - cmake ..; make -j; make install
    - make -j run_py_sample
  artifacts:
    name: coverage
    paths:
      - cov_result

# -------------------- Lints --------------------
cppcheck:
  stage: lint
  image: registry.cn-hangzhou.aliyuncs.com/leosocy/cppcheck:1.83
  script:
    - cppcheck --enable=warning --error-exitcode=1 -I source/include source/src

# -------------------- Cov --------------------