stages:
  - test
  - lint
  - deploy_integration

test:
  stage: test
  image: "registry.cn-hangzhou.aliyuncs.com/leosocy/opencv:3.4.1"
  script:
    - mkdir -p build; cd build
    - cmake ../test; make -j
    - ./test_edcc