language: cpp

sudo: required

services:
  - docker

env:
  - CI=true

cache:
  directories:
    - $HOME/docker

before_cache:
  - ./manage.sh save_images


stages:
  - tests_and_lints
  - name: upload_codecov
    if: branch = master AND type = push
  - name: build_image
    if: branch = master AND type = push

jobs:
  include:
    - stage: tests_and_lints
      name: test
      script:
        - ./manage.sh test
    - stage: tests_and_lints
      name: lint
      script:
        - ./manage.sh lint
    - stage: upload_codecov
      name: upload codecov report
      script:
        - ./manage.sh upload_codecov
    - stage: build_image
      name: build image
      script:
        - ./manage.sh build_images
        - ./manage.sh upload_images

